version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ff-ping-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18xu03a1ma93b"
s3_prefix = "ff-ping-app"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
