AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DomainName:
    Type: String
    Description: Domain name for api
    Default: ping.flowforge.com
  CertArn:
    Type: String

Resources:
  PingDB:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: flowforge-ping-data
      AttributeDefinitions:
        - AttributeName: "instanceId"
          AttributeType: "S"
        - AttributeName: "createdAt"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "instanceId"
          KeyType: "HASH"
        - AttributeName: "createdAt"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  HttpApiGateway: # Creates a HTTP API endpoint under the customm domain
    Type: AWS::Serverless::HttpApi
    Properties:
      Domain:
        DomainName: !Ref DomainName
        CertificateArn: !Ref CertArn

  LambdaPingHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs14.x
      MemorySize: 128
      Events:
        apiForLambda:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApiGateway
            Method: post
            Path: /ping
      Policies:
        DynamoDBWritePolicy:
          TableName: !Ref PingDB
